#!/usr/bin/env python3
"""Rebuild the dedicated Llama2-70B 128K balanced equal-power analysis.

This wrapper consumes the corrected TP=1/2/4/8/16 sources generated by the
consolidated experiment.  Each exact-divisor PP sweep starts at TP=1 and ends
after the first Bmax > PP point.  Only Bmax=0 is rejected; a partially filled
pipeline remains valid with throughput and idle power scaled by its fill.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

import pandas as pd

_CENT_SIM_IMPORT_ROOT = Path(__file__).resolve().parents[1]
if str(_CENT_SIM_IMPORT_ROOT) not in sys.path:
    sys.path.insert(0, str(_CENT_SIM_IMPORT_ROOT))
from scripts import analyze_balanced_equal_power as common


ROOT = Path(__file__).resolve().parents[2]
CENT_SIM = Path(__file__).resolve().parents[1]
MODEL = "Llama2-70B"
CONTEXT = "128K"
CONTEXT_WINDOW = 131072
PP_VALUES = common.exact_pp_values(MODEL)
TP_VALUES = (1, 2, 4, 8, 16)
DEFAULT_RAW_ROOT = CENT_SIM / "output/balanced_equal_power_all_contexts/raw"
DEFAULT_OUTPUT_DIR = CENT_SIM / "output/balanced_equal_power_70b_128k/analysis"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw-root", type=Path, default=DEFAULT_RAW_ROOT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--h100-profile", type=Path, default=ROOT / "DGX_H100_profile_results.csv")
    parser.add_argument("--device-capacity-gib", type=float, default=16.0)
    parser.add_argument("--reserve-gib", type=float, default=0.0)
    parser.add_argument("--dram-energy-model", choices=common.cent.DRAM_ENERGY_MODELS, default="legacy")
    parser.add_argument("--no-plots", action="store_true")
    return parser.parse_args()


def display_path(path: Path) -> str:
    resolved = path.resolve()
    try:
        return str(resolved.relative_to(ROOT))
    except ValueError:
        return str(resolved)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def capacity_for_candidate(
    pp: int,
    tp: int,
    device_capacity_gib: float,
    reserve_gib: float,
) -> dict[str, float | int]:
    """Compatibility helper retained for focused tests and interactive use."""

    return common.capacity_for_candidate(
        MODEL,
        CONTEXT_WINDOW,
        pp,
        tp,
        device_capacity_gib,
        reserve_gib,
    )


def narrow_envelope(device_capacity_gib: float, reserve_gib: float) -> pd.DataFrame:
    envelope = common.sweep_envelope(device_capacity_gib, reserve_gib)
    return envelope[
        (envelope["Model"] == MODEL) & (envelope["Context"] == CONTEXT)
    ].copy()


def build_candidates(
    raw_root: Path,
    device_capacity_gib: float,
    reserve_gib: float,
    dram_energy_model: str,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, dict[str, str]]]:
    envelope = narrow_envelope(device_capacity_gib, reserve_gib)
    required_tps = common.required_tps(envelope, MODEL, CONTEXT)
    if required_tps != TP_VALUES:
        raise ValueError(f"unexpected 70B/128K TP envelope: {required_tps}")

    rows: list[dict[str, object]] = []
    source_manifest: dict[str, dict[str, str]] = {}
    for memory, memory_config in common.MEMORY_CASES.items():
        source_path = raw_root / Path(memory_config["csv"])
        sources = common.load_tp_sources(
            source_path,
            MODEL,
            CONTEXT,
            required_tps,
            dram_energy_model,
        )
        source_manifest[memory] = {
            "path": display_path(source_path),
            "sha256": sha256(source_path),
        }
        for point in envelope.itertuples(index=False):
            pp = int(point.PP)
            tp = int(point.TP)
            rows.append(
                common.build_candidate(
                    memory,
                    str(memory_config["dram_impl"]),
                    source_path,
                    sources[tp],
                    MODEL,
                    CONTEXT,
                    pp,
                    tp,
                    device_capacity_gib,
                    reserve_gib,
                )
            )
    candidates = common.assign_ranks(pd.DataFrame(rows)).sort_values(
        ["Memory", "PP", "TP"]
    )
    return envelope, candidates, source_manifest


def point_annotation(row: pd.Series | object) -> str:
    if isinstance(row, pd.Series):
        bmax = int(row["Max resident microbatch"])
        fill = float(row["Pipeline fill ratio"])
    else:
        bmax = int(getattr(row, "Max_resident_microbatch"))
        fill = float(getattr(row, "Pipeline_fill_ratio"))
    return f"B={bmax} | U={fill:.0%}"


def write_metric_plot(
    candidates: pd.DataFrame,
    metric: str,
    ylabel: str,
    title: str,
    filename: str,
    output_dir: Path,
) -> None:
    import matplotlib.pyplot as plt
    from matplotlib.lines import Line2D

    plt.style.use("seaborn-v0_8-whitegrid")
    plt.rcParams.update(
        {
            "font.size": 12,
            "axes.titlesize": 16,
            "axes.labelsize": 14,
            "xtick.labelsize": 12,
            "ytick.labelsize": 12,
            "legend.fontsize": 12,
        }
    )
    memories = list(common.MEMORY_CASES)
    pp_positions = {pp: index for index, pp in enumerate(PP_VALUES)}
    # Keep the samples exactly on their categorical PP positions.  Only the
    # annotations are fanned in display coordinates so coincident TP results
    # remain legible without making the x coordinates look misaligned.
    label_offsets = dict(zip(TP_VALUES, (-24, -12, 0, 12, 24)))
    tp_colors = {
        tp: common.SEABORN_COLORBLIND[index]
        for index, tp in enumerate(TP_VALUES)
    }

    fig, axes = plt.subplots(
        1,
        len(memories),
        figsize=(21, 8.2),
        sharex=True,
        sharey=False,
        gridspec_kw={"width_ratios": [1, 1, 1]},
    )
    for ax, memory in zip(axes, memories):
        memory_rows = candidates[candidates["Memory"] == memory]
        for tp in TP_VALUES:
            rows = memory_rows[memory_rows["TP"] == tp].sort_values("PP")
            if rows.empty:
                continue
            # Every point is placed exactly on its PP tick.  Text is fanned
            # out independently in display coordinates when TP curves meet.
            x_values = [pp_positions[int(pp)] for pp in rows["PP"]]
            admitted = rows["Can host one request"].to_numpy(dtype=bool)
            admitted_rows = rows[admitted]
            admitted_x = [x for x, keep in zip(x_values, admitted) if keep]
            rejected_rows = rows[~admitted]
            rejected_x = [x for x, keep in zip(x_values, admitted) if not keep]

            if len(admitted_rows) > 1:
                ax.plot(
                    admitted_x,
                    admitted_rows[metric],
                    color=tp_colors[tp],
                    linewidth=1.5,
                    alpha=0.45,
                    zorder=2,
                )
            if not admitted_rows.empty:
                ax.scatter(
                    admitted_x,
                    admitted_rows[metric],
                    color=tp_colors[tp],
                    edgecolor="white",
                    linewidth=0.6,
                    s=66,
                    zorder=3,
                )
            if not rejected_rows.empty:
                ax.scatter(
                    rejected_x,
                    rejected_rows[metric],
                    color=common.SEABORN_COLORBLIND[7],
                    marker="x",
                    linewidth=1.4,
                    s=58,
                    zorder=3,
                )

            for x_value, (_, row) in zip(x_values, rows.iterrows()):
                admitted_point = bool(row["Can host one request"])
                ax.annotate(
                    point_annotation(row),
                    (x_value, float(row[metric])),
                    xytext=(label_offsets[tp], 7),
                    textcoords="offset points",
                    ha="center",
                    va="bottom",
                    fontsize=8.0,
                    rotation=90,
                    color=("#303030" if admitted_point else common.SEABORN_COLORBLIND[7]),
                    zorder=4,
                )

        maximum = float(memory_rows[metric].max())
        upper = maximum * 1.38 if maximum > 0.0 else 1.0
        ax.set_ylim(0.0, upper)
        ax.set_xlim(-0.55, len(PP_VALUES) - 0.45)
        ax.axhline(0.0, color="#777777", linewidth=0.8)
        ax.set_xticks(range(len(PP_VALUES)), PP_VALUES)
        ax.set_xlabel("PP (exact divisor of 80)")
        ax.set_ylabel(ylabel)
        ax.set_title(memory)
        ax.grid(axis="y", alpha=0.28)

    legend_handles = [
        Line2D(
            [0],
            [0],
            color=tp_colors[tp],
            marker="o",
            linewidth=1.2,
            markersize=6,
            label=f"TP={tp}",
        )
        for tp in TP_VALUES
    ]
    legend_handles.append(
        Line2D(
            [0],
            [0],
            color=common.SEABORN_COLORBLIND[7],
            marker="x",
            linewidth=0,
            markersize=7,
            label="Bmax=0 (rejected)",
        )
    )
    fig.suptitle(
        f"{title}\npoint label: B=in-flight request capacity | U=pipeline utilization",
        y=0.995,
        fontsize=18,
    )
    fig.legend(
        handles=legend_handles,
        loc="upper center",
        bbox_to_anchor=(0.5, 0.91),
        ncols=6,
        frameon=False,
        fontsize=12,
    )
    fig.subplots_adjust(left=0.055, right=0.985, bottom=0.12, top=0.78, wspace=0.24)
    for suffix in ("png", "pdf"):
        fig.savefig(output_dir / f"{filename}.{suffix}", dpi=240, bbox_inches="tight")
    plt.close(fig)


def write_plots(candidates: pd.DataFrame, output_dir: Path) -> None:
    write_metric_plot(
        candidates,
        "Throughput / device (tokens/s/device)",
        "Throughput/device (tokens/s/device)",
        "Llama2-70B, 128K: capacity-constrained throughput/device",
        "throughput_per_device",
        output_dir,
    )
    write_metric_plot(
        candidates,
        "Tokens/J",
        "Tokens/J",
        "Llama2-70B, 128K: capacity-constrained token efficiency",
        "tokens_per_joule",
        output_dir,
    )


def write_readme(
    output_dir: Path,
    candidates: pd.DataFrame,
    selected: pd.DataFrame,
) -> None:
    admitted = candidates[candidates["Can host one request"]]
    selected_rows = selected[
        [
            "Memory",
            "Objective",
            "PP",
            "TP",
            "Max resident microbatch",
            "Microbatch used",
            "Pipeline fill ratio",
            "Throughput / device (tokens/s/device)",
            "Tokens/J",
        ]
    ]
    table = common.markdown_table(selected_rows, list(selected_rows.columns))
    text = f"""# Llama2-70B 128K balanced equal-power post-processing

This directory is rebuilt from the corrected consolidated TP=1/2/4/8/16
Ramulator sources. It uses BF16, 16 GiB/device, exact divisors of 80 for PP,
inter-device attention, and fully TP-sharded KV cache.

Every PP sweep begins at TP=1 and includes the first point with `Bmax > PP`.
Only `Bmax=0` is rejected. The other {len(admitted) // len(common.MEMORY_CASES)}
PP/TP points per memory case remain valid, including partial pipeline fill.

For plot labels, the supported in-flight request capacity is `Bmax`, while
pipeline utilization is `min(Bmax, PP) / PP`. Gray crosses are the only
rejected points.

Throughput/device and tokens/J are ranked independently. Both happen to select
the same layout for each memory timing in this dataset:

{table}

## Files

- `sweep_envelope.csv`: all 35 evaluated PP/TP points before memory timing.
- `all_candidates.csv`: 105 memory-specific points; only Bmax=0 lacks a rank.
- `rank_throughput_per_device.csv` and `rank_tokens_per_joule.csv`: all 66
  admitted memory-specific points.
- `selected_base_configs.csv`: deterministic rank-1 choices for both objectives.
- `equal_power_deployments.csv`: floor/ceil DP neighbors around DGX power.
- `throughput_per_device` and `tokens_per_joule` PNG/PDF figures: every point
  annotated as `B=in-flight capacity | U=utilization`.
"""
    (output_dir / "README.md").write_text(text)


def main() -> int:
    args = parse_args()
    if args.device_capacity_gib <= args.reserve_gib:
        raise ValueError("device capacity must exceed the per-device reserve")
    raw_root = args.raw_root.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    envelope, candidates, sources = build_candidates(
        raw_root,
        args.device_capacity_gib,
        args.reserve_gib,
        args.dram_energy_model,
    )
    admitted = candidates[candidates["Can host one request"]].copy()
    throughput_rank = admitted.sort_values(
        ["Memory", "Throughput/device rank", "PP", "TP"]
    )
    tokens_rank = admitted.sort_values(["Memory", "Tokens/J rank", "PP", "TP"])
    selected = common.choose_base_configs(candidates).sort_values(["Memory", "Objective"])
    dgx = common.load_dgx(args.h100_profile.resolve())
    deployments = common.build_equal_power_deployments(selected, dgx).sort_values(
        ["Memory", "Objective", "DP"]
    )

    outputs = {
        "sweep_envelope.csv": envelope,
        "all_candidates.csv": candidates,
        "rank_throughput_per_device.csv": throughput_rank,
        "rank_tokens_per_joule.csv": tokens_rank,
        "selected_base_configs.csv": selected,
        "equal_power_deployments.csv": deployments,
    }
    for filename, dataframe in outputs.items():
        path = output_dir / filename
        dataframe.to_csv(path, index=False)
        print(f"[data] {display_path(path)}")

    manifest = {
        "model": MODEL,
        "context": CONTEXT,
        "context_window": CONTEXT_WINDOW,
        "active_sequence_length": common.CONTEXTS[CONTEXT]["active"],
        "precision": common.PRECISION,
        "device_capacity_gib": args.device_capacity_gib,
        "reserve_gib": args.reserve_gib,
        "pp_values": list(PP_VALUES),
        "tp_values": list(TP_VALUES),
        "admission_rule": "Bmax >= 1",
        "in_flight_request_capacity": "Bmax",
        "pipeline_occupied_requests": "min(Bmax, PP)",
        "pipeline_utilization": "min(Bmax, PP) / PP",
        "attention_mapping": "inter_device",
        "kv_mapping": "fully_tp_sharded",
        "dram_energy_model": args.dram_energy_model,
        "sources": sources,
    }
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    write_readme(output_dir, candidates, selected)

    if not args.no_plots:
        write_plots(candidates, output_dir)
        print(f"[plots] {display_path(output_dir)}")

    print(
        selected[
            [
                "Memory",
                "Objective",
                "PP",
                "TP",
                "Max resident microbatch",
                "Microbatch used",
                "Pipeline fill ratio",
                "Throughput / device (tokens/s/device)",
                "Tokens/J",
            ]
        ].to_string(index=False, float_format=lambda value: f"{value:.6g}")
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
